### ISSUE TITLE
Last update won't start in docker

### ISSUE THREAD

**Issue by DonkeyHotNew** [netdata/netdata#11494]
##### Bug report summary
Last update won't start in docker

##### OS / Environment
Ubuntu 20.04 LTS

##### Netdata version
latest: Pulling from netdata/netdata
e519532ddf75: Pull complete
eb40d12b1e37: Pull complete
8dc89d5ada7f: Pull complete
ec48cede855b: Pull complete
a012af41805b: Pull complete
1f9d96966d9b: Pull complete
Digest: sha256:f03b9f47c22fc0f9a564053e27986a37645e40b36d630cde099da29ed6cfef5b

ID sha256:b209401bb54224816a1cf744c22c1f51ab3731972c49f7c4f3cf82b2c8a6b494
Size 336.5 MB
Created 2021-09-08 18:07:50
Build: Docker on linux, amd64

##### Installation method
docker run -d --name=netdata \
  -p 19999:19999 \
  -v netdataconfig:/etc/netdata \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  netdata/netdata

##### Component Name
Container will not start with error log full of the same messages:

ls: /var/run/balena.sock: No such file or directory
ls: /var/run/docker.sock: No such file or directory
Account databases are not writable, assuming you know what you’re doing and continuing.
chown: unknown user/group netdata:root
ls: /var/run/balena.sock: No such file or directory
ls: /var/run/docker.sock: No such file or directory
Account databases are not writable, assuming you know what you’re doing and continuing.
chown: unknown user/group netdata:root
ls: /var/run/balena.sock: No such file or directory
ls: /var/run/docker.sock: No such file or directory
Account databases are not writable, assuming you know what you’re doing and continuing.

**Comment by ilyam8** [comment]
@DonkeyHotNew, thanks for the bug report 👍

**Comment by wbulot** [comment]
I confirm today's latest version does not work on any of my docker environments.

**Comment by ipeacocks** [comment]
As I've got you don't use proper docker image tagging. So only `latest` and `v1.31.0` tags (4 month old one). Thus, there is no way to use older one image.

**Comment by WalkxCode** [comment]
Same issue.

**Comment by Ferroin** [comment]
This should be fixed on the `latest` tag once tonight’s nightlies get published (some time around 2021-09-10 01:00 UTC).

As far as the tagging, we do not have explicit tags for our old nightly builds. `latest` tracks whatever was most recently pubished (be it a nightly or stable version), `stable` trackes the latest stable release (as of right now equivalent to `v1.31.0`, though there should hopefully be a new stable release later this month or early next month), and `edge` explicitly tracks only nightly builds.

**Comment by fuomag9** [comment]
I confirm the issue as well

**Comment by NicolasCARPi** [comment]
Thanks @ilyam8 for the rapid fix! :)

**Comment by SR-G** [comment]
Hi. I still have that exact same error (with latest image), but on ARM64 ... have the ARM images been pushed with the correction ?


```
docker pull netdata/netdata
(...)
Using default tag: latest
latest: Pulling from netdata/netdata
Digest: sha256:b6bb722b7bb5d0818367ba066987ebe3f84b4e3cea98799674d535b924e3aa85
Status: Image is up to date for netdata/netdata:latest
```

```
uname -a
Linux helios4 5.10.60-mvebu #21.08.1 SMP Wed Aug 25 18:44:04 UTC 2021 armv7l GNU/Linux
```

Regular start (was working previously), but log is : 

```
ls: /var/run/balena.sock: No such file or directory
Netdata detected docker.sock
Creating docker group 117
Assign netdata user to docker group 117
```
