### ISSUE TITLE
[Bug]: netdata agent eats memory

### ISSUE THREAD

**Issue by bluepuma77** [netdata/netdata#16412]
### Bug description

```
root@backup1 ~ # docker stats --all --no-stream
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
00dd46cdf0a4   netdata        43.82%    3.838GiB / 4GiB       95.95%    27.7MB / 193MB    48.1GB / 164GB    86
```

### Expected behavior

Netdata stays with a small memory footprint, even running for months.
```
root@db-201 ~ # docker stats --all --no-stream
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
cb42bcf2a21f   netdata        3.78%     311.6MiB / 125.8GiB   0.24%     49MB / 77.2MB     2.27TB / 225GB    102
```

### Steps to reproduce

V=v1.43.2 && IP=10.0.0.1

docker pull netdata/netdata:$V

docker stop netdata ; docker rm netdata
 
docker run -d --name=netdata \
  -p $IP:19999:19999 \
  -v netdataconfig:/etc/netdata \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -e DISABLE_TELEMETRY=0 \
  -e NETDATA_CLAIM_TOKEN=q3ZUOF...ssfBPQ  \
  --hostname $(hostname) \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  --memory=4096m \
  --memory-swap=4096m \
  netdata/netdata:$V

### Installation method

docker

### System info

```shell
root@backup1 ~ # uname -a; grep -HvE "^#|URL" /etc/*release
Linux backup1 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
root@backup1 ~ # docker exec -it netdata sh
/ # netdata -W buildinfo
Packaging:
    Netdata Version ____________________________________________ : v1.43.2
    Installation Type __________________________________________ : oci
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ : unknown
    Configure Options __________________________________________ :  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--enable-lto' '--disable-ebpf' 'CFLAGS=-ffunction-sections -fdata-sections -O2 -funroll-loops -pipe' 'LDFLAGS=-Wl,--gc-sections'
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 5.10.0-22-amd64
    Operating System ___________________________________________ : Debian GNU/Linux
    Operating System ID ________________________________________ : debian
    Operating System ID Like ___________________________________ : unknown
    Operating System Version ___________________________________ : 11 (bullseye)
    Operating System Version ID ________________________________ : 3.18.4
    Detection __________________________________________________ : /host/etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 12
    CPU Frequency ______________________________________________ : 3900000000
    CPU Architecture ___________________________________________ : 135041257472
    RAM Bytes __________________________________________________ : 78007880384512
    Disk Capacity ______________________________________________ : x86_64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : none
Container:
    Container __________________________________________________ : docker
    Container Detection ________________________________________ : dockerenv
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : Alpine Linux
    Container Operating System ID ______________________________ : alpine
    Container Operating System ID Like _________________________ : unknown
    Container Operating System Version _________________________ : unknown
    Container Operating System Version ID ______________________ : 3.18.4
    Container Operating System Detection _______________________ : /etc/os-release
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (lz4)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    map ________________________________________________________ : YES
    save _______________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : NO
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Judy (high-performance dynamic arrays and hashtables) ______ : YES (bundled)
    dlib (robust machine learning toolkit) _____________________ : YES (bundled)
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libm (mathematical functions) ______________________________ : YES
    jemalloc ___________________________________________________ : NO
    TCMalloc ___________________________________________________ : NO
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : NO
    ebpf (monitor system calls) ________________________________ : NO
    freeipmi (monitor enterprise server H/W) ___________________ : YES
    nfacct (gather netfilter accounting) _______________________ : NO
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : YES
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
/ #
```

### Additional info

As stated in a [previous issue](https://github.com/netdata/netdata/issues/15066), which I closed wrongly because I thought it was resolved:

The netdata container is running on a Debian Linux server with big RAID storage. On the same host we continuously are start and run `mongodump` Docker containers to create backups from databases on a remote MongoDB cluster. During the day around 4000 containers are started and terminated, running between 5 seconds to 5 minutes.

**Comment by bluepuma77** [comment]
Netdata is up for 4 days, consumer 2GB of RAM
```
# docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED         STATUS                PORTS                                       NAMES
00dd46cdf0a4   netdata/netdata:v1.43.2   "/usr/sbin/run.sh"       2 weeks ago     Up 4 days (healthy)   10.0.0.22:19999->19999/tcp                  netdata

docker stats --all --no-stream
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
00dd46cdf0a4   netdata        113.61%   2.052GiB / 4GiB       51.30%    38MB / 306MB      26.7GB / 45.2GB   85
```

**Comment by bluepuma77** [comment]
Current status:
```
#docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED       STATUS                 PORTS                                       NAMES
00dd46cdf0a4   netdata/netdata:v1.43.2   "/usr/sbin/run.sh"       3 weeks ago   Up 12 days (healthy)   10.0.0.22:19999->19999/tcp                  netdata
...

# docker stats --all --no-stream
CONTAINER ID   NAME                    CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
00dd46cdf0a4   netdata                 71.81%    3.903GiB / 4GiB       97.58%    57.8MB / 449MB    51.4GB / 154GB    85
...
```

Created a `netdata.conf` and mounted it into the netdata container, killed volumes, restarted. Lets see what happens.
```
[db]
	cleanup obsolete charts after secs = 600
```

**Comment by bluepuma77** [comment]
Thanks to messing with the config, I found `http://<ip>:19999/netdata.conf` which shows the current config.

It seems my config is continuously growing with such entries with different IDs:
```
[plugin:proc:/proc/net/dev:veth500e36c]
	# enabled = yes
	# virtual = yes
	# bandwidth = yes
	# packets = auto
	# errors = auto
	# drops = auto
	# fifo = auto
	# compressed = auto
	# events = auto
	# speed = auto
	# duplex = auto
	# operstate = auto
	# carrier = auto
	# mtu = auto
```
Can this be disabled?

**Comment by ilyam8** [comment]
@bluepuma77 nice finding, I fixed the issue in #16492. A better solution would probably be to remove the creation of these config sections for each network interface. I'm not sure we even need them, but we need to check.

**Comment by bluepuma77** [comment]
I updated to a recent `latest` Docker image with the patch included. It solves the config issue, running `curl http://10.0.0.22:19999/netdata.conf | wc -l` show <1000 lines, not continuously growing.

But the memory issue seems still not solved, in 6 days `netdata` has grown to 2GB RAM.

```
# docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED              STATUS                 PORTS                                       NAMES
cd4699d07382   mongo:6                   "docker-entrypoint.s…"   About a minute ago   Up About a minute      27017/tcp                                   mongodump-2023-12-08T12-06-58
02f832edebcf   netdata/netdata:latest    "/usr/sbin/run.sh"       6 days ago           Up 6 days (healthy)    10.0.0.22:19999->19999/tcp                  netdata
```
```
# docker stats --all --no-stream
CONTAINER ID   NAME                                   CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
cd4699d07382   mongodump-2023-12-08T12-06-58          114.38%   110.6MiB / 125.8GiB   0.09%     2GB / 7.03MB      0B / 0B           17
02f832edebcf   netdata                                5.89%     2.033GiB / 4GiB       50.82%    2.05MB / 928kB    43.7GB / 58.6GB   148
``` 
Will update to new `v1.44` and report back in a couple of days.

**Comment by bluepuma77** [comment]
Uptime 8 days, 4GB RAM usage.

Netdata itself sent me a message 8 days ago: `netdata docker container health status is unhealthy`, when it was probably last restarted.

```
# docker ps
CONTAINER ID   IMAGE                                     COMMAND                  CREATED         STATUS                 PORTS                                       NAMES
987bf5b4c2da   netdata/netdata:v1.44                     "/usr/sbin/run.sh"       3 weeks ago     Up 8 days (healthy)    10.0.0.22:19999->19999/tcp                  netdata
```
```
# docker stats --all --no-stream
CONTAINER ID   NAME                                                                           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
987bf5b4c2da   netdata                                                                        116.03%   3.895GiB / 4GiB       97.38%    24.7MB / 174MB    46.1GB / 150GB    154
```

Will update to `v1.44.1` and report back.

**Comment by bluepuma77** [comment]
Running netdata v1.44.1, it took 2 weeks to use up 4GB of RAM
```
# docker ps -a
CONTAINER ID   IMAGE                     COMMAND                  CREATED        STATUS                  PORTS                                       NAMES
3dde9daab542   netdata/netdata:v1.44.1   "/usr/sbin/run.sh"       2 weeks ago    Up 2 weeks (healthy)    10.0.0.22:19999->19999/tcp                  netdata
```
```
# docker stats --all --no-stream
CONTAINER ID   NAME                                   CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
5cbedf97dca8   mongodump-2024-01-19T20-15-53          66.85%    102.1MiB / 125.8GiB   0.08%     419MB / 1.36MB    0B / 0B           17
3dde9daab542   netdata                                208.09%   3.925GiB / 6GiB       65.41%    17.1MB / 68.5MB   42.4GB / 93.8GB   155
```

**Comment by bluepuma77** [comment]
v1.44.3, 3GB RAM after 2 weeks
```
# docker ps 
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS                  PORTS                                       NAMES
f0609b454623   netdata/netdata:v1.44.3   "/usr/sbin/run.sh"       2 weeks ago      Up 2 weeks (healthy)    10.0.0.22:19999->19999/tcp                  netdata
```
```
# docker stats --all --no-stream
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
f0609b454623   netdata        20.71%    2.824GiB / 6GiB       47.07%    29.1MB / 154MB    95.8GB / 81.9GB   156```

**Comment by bluepuma77** [comment]
Up 5 weeks, consuming 4.5GB of RAM, using 7% CPU on a 12 core machine with big RAID setup and lots of containers starting and stopping
```
# docker ps
CONTAINER ID   IMAGE                             COMMAND                  CREATED       STATUS                 PORTS                                       NAMES
f0609b454623   netdata/netdata:v1.44.3           "/usr/sbin/run.sh"       5 weeks ago   Up 5 weeks (healthy)   10.0.0.22:19999->19999/tcp                  netdata
```
```
# docker stats --all --no-stream
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
f0609b454623   netdata        7.30%     4.662GiB / 6GiB       77.70%    57.8MB / 317MB    111GB / 160GB     156
```
Now upgrading to v1.45.0, removed all volumes to avoid any incompatibilities.

**Comment by bluepuma77** [comment]
Kind of unhappy here. It seems you have a memory leak and nothing is done about it - for 6 months already.

```
# docker stats --all --no-stream
CONTAINER ID   NAME     CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
d83e0b10b3bb   netdata  28.61%    3.126GiB / 6GiB       52.10%    1.52GB / 3.44GB   15GB / 99.6GB     172

# docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED         STATUS                PORTS                       NAMES
d83e0b10b3bb   netdata/netdata:v1.45.0   "/usr/sbin/run.sh"       5 weeks ago     Up 4 days (healthy)   10.0.0.22:19999->19999/tcp  netdata
```

Just started a new instance `v1.45.3`. When using old volumes, it immediately consumer 500MB RAM. Stopped instance, removed volumes, started again. Let's see what happens.

---

Update, running v1.45.3 for 2 weeks, same result:
```
# docker stats --all --no-stream 
CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
4f77507b48fe   netdata    13.18%    2.936GiB / 6GiB       48.94%    27.5GB / 62.6GB   24.4GB / 104GB    172

# docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED       STATUS                 PORTS                                       NAMES
4f77507b48fe   netdata/netdata:v1.45.3   "/usr/sbin/run.sh"       2 weeks ago   Up 2 weeks (healthy)   10.0.0.22:19999->19999/tcp                  netdata
```
---
Next try with `v1.45.4`.

**Comment by rafaelreis-r** [comment]
I'm running into similar issues in my ubuntu hosts, recent install (2wks old) and memory is leaking in all of them:

`4cd8857cc459   netdata                            22.88%    4.666GiB / 30.6GiB   15.25%    0B / 0B           213GB / 24.6GB    130`

<img width="688" height="327" alt="Image" src="https://github.com/user-attachments/assets/c2a263c7-02eb-4d26-8a8b-62ab44a44c06" />
Netdata at the top

`9ef304fb44f1   netdata                          10.75%    979.3MiB / 15.24GiB   6.27%     0B / 0B           29GB / 12.3GB     102`

<img width="726" height="342" alt="Image" src="https://github.com/user-attachments/assets/62ea6b16-da48-4f34-aed8-a72f2f8cb813" />

What else can I provide to help track this down @bluepuma77 ?
