### ISSUE TITLE
[Feat]: Windows installer issues

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#18213]
### Problem

Our current Windows installer has some issues.

### Description

1. Installation Directory should be `C:\Program Files\Netdata`, (with a capital `N`). (https://github.com/netdata/netdata/pull/18227)
2. The installer should be able to update a running Netdata service (https://github.com/netdata/netdata/pull/18253).
3. The following files are not needed:
	- `etc/default/netdata`
	- `etc/init.d/netdata`
	- `etc/logrotate.d/netdata`
	- `etc/netdata/edit-config`
	- `etc/netdata/netdata-updater.conf`
	- all files in `lib/systemd/system`
	- `lib/systemd/journal@netdata.conf.d/netdata.conf`
	- all files in `usr/share/doc`
4. The following plugins are not needed (in `usr/libexec/netdata/plugins.d`):
	- `acl.sh`
	- `alarm.sh`
	- `alarm-email.sh`
	- `cgroup-name.sh`
	- `cgroup-network-helper.sh`
	- `ebpf_thread_function.sh`
	- `get-kubernetes-labels.sh`
	- `health-cmdapi-test.sh`
	- `request.sh`
	- `system-info.sh`
	- `tc-qos-helper.sh`
	- `template_dim.sh`
5. The installer should be signed/verified (today it is falsely detected as a trojan horse)
6. The updater should either work on windows, or be removed (multiple files)
7. Make the installer ask for Netdata Cloud Space token and rooms to generate `etc/netdata/claim.conf`. If claim.conf is already present, it should not ask for this information (https://github.com/netdata/netdata/pull/18410)
8. go.d.plugin should be shipped with Netdata.
9. We should give users the option to somehow get an msys prompt. (https://github.com/netdata/netdata/pull/18385)

### Importance

blocker

### Value proposition

1. Do not install unecesary files on windows
2. Have the installer signed
3. Make the updater work, or remove it
4. Make the installer install claim.conf so that all windows installations are claimed.
5. go.d.plugin should be shipped with Netdata on Windows
6. The installer should be able to update a running Netdata.

**Comment by stelfrag** [comment]
@Ferroin , @thiagoftsm Have a look

**Comment by Ferroin** [comment]
Regarding the updater, I’m hesitant to support auto-updates on Windows until we actually get asked to provide such functionality by customers given that our target users are large companies. They’re the demographic that’s most likely to disable auto-updates so that they can manage things themselves.

Regarding claiming, we absolutely should also have a way to specify claiming parameters on the installer command line. That’s the way people are going to expect things to work when automating the install process.

**Comment by Ferroin** [comment]
A few other things that still need done before this is all ready for a proper release:

- We need to switch to a proper Release or ReleaseWithDebInfo build instead of a Debug build. This will remove most of the ‘plugins’ that are not needed, and will also remove the need to add `-fstack-protector-strong` to the CFLAGS.
- We need to get rid of `-DNETDATA_INTERNAL_CHECKS` in the CFLAGS
- We need to get rid of the `-O0` in the CFLAGS (and probably `-ggdb`)
- We need to get rid of `-DDEFAULT_FEATURE_STATE=Off` in the CMake options for Windows and explicitly call out what needs to be disabled (or, better yet, make the options depend on not being built on Windows in the CMake file, like we do for most of our plugins right now). This should result in Go being built and shipped.

**Comment by ktsaou** [comment]
The installer failed to write files when the Netdata service is already running.
Users has to stop the service for installer to work.

So, the installer should stop the Netdata service to update it.

**Comment by ktsaou** [comment]
@Ferroin we really need go.d.plugin in the installer.
We have spent a tremendous amount of money to make external plugins work in Netdata for Windows. Please include it.

**Comment by thiagoftsm** [comment]
> So, the installer should stop the Netdata service to update it.

We already added in Windows Registry variables to monitor Netdata version as the first step in this direction.
Now that I merged the first PR addressing the requests in this issue, the next will have bring this.

**Comment by Ferroin** [comment]
> The installer failed to write files when the Netdata service is already running. Users has to stop the service for installer to work.
> 
> So, the installer should stop the Netdata service to update it.

This brings up something we need to make a point to remember about Windows: Unlike POSIX systems, files that are in-use can almost never be replaced in-place on Windows. This is an inherent limitation of the Windows VFS combined with how most things (including the kernel when loading executables and libraries) interact with files.

**Comment by thiagoftsm** [comment]
> This brings up something we need to make a point to remember about Windows: Unlike POSIX systems, files that are in-use can almost never be replaced in-place on Windows. This is an inherent limitation of the Windows VFS combined with how most things (including the kernel when loading executables and libraries) interact with files.

Exactly. I also understand we should popup for users the information that we are doing an update and if they want to proceed. After the confirmation, we have to stop the service and proceed with installation.

We also can add an option for installer to do a possible force update without show the default popup.

**Comment by Ferroin** [comment]
Quick update on this from my end:

- Most of item 4 was resolved by #18230.
- Item 3 and the rest of item 4 will be mostly fixed indirectly by #18010, with the remainder of the fixes being largely dependent on changes that are in that PR. If it’s not merged by 2024-08-09 I plan to split out the required changes for the Windows side of things as a separate PR.
- Item 5 will be fixed by #18222. There’s a CI failure there that I’ve been trying to reproduce unsuccessfully for more than a week now that really needs to be addressed before it gets merged.
- Item 6 will need it’s own PR, but that should take less than 24 hours from starting work until it’s merged.
- Item 8 was resolved by #18229.
- The issues I brought up in https://github.com/netdata/netdata/issues/18213#issuecomment-2250602411 have been fixed by #18229 and #18230.

Everything else is tied to the installer code, which has thus far not been part of my area of concern.

**Comment by Ferroin** [comment]
Item 6 will be resolved by #18251.

**Comment by thiagoftsm** [comment]
Item 2 will be resolved by https://github.com/netdata/netdata/pull/18253

**Comment by thiagoftsm** [comment]
@Ferroin I am still having some local issues with https://github.com/netdata/netdata/pull/18010 that fixed `3` and `4`, let me know how I can help you for we finish this.

**Comment by thiagoftsm** [comment]
@Ferroin since yesterday I am observing this issue with GO:

```sh
+ /usr/bin/cmake -S /home/thiago/Netdata/netdata -B /home/thiago/Netdata/netdata/build-msys-MSYS -G Ninja -DCMAKE_INSTALL_PREFIX=/opt/netdata -DBUILD_FOR_PACKAGING=On -DNETDATA_USER=thiago -DENABLE_ACLK=On -DENABLE_CLOUD=On -DENABLE_H2O=Off -DENABLE_ML=On -DENABLE_PLUGIN_GO=On -DENABLE_EXPORTER_PROMETHEUS_REMOTE_WRITE=Off -DENABLE_BUNDLED_JSONC=On -DENABLE_BUNDLED_PROTOBUF=Off
go: cannot find GOROOT directory: 'go' binary is trimmed and GOROOT is not set
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find Go: (Required is at least version "1.22.0") (found
  /mingw64/bin/go.exe)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:601 (_FPHSA_FAILURE_MESSAGE)
  packaging/cmake/Modules/FindGo.cmake:48 (find_package_handle_standard_args)
  CMakeLists.txt:212 (find_package)
```

Probably we are missing something in our script that installs dependencies.

**Comment by thiagoftsm** [comment]
> We should give users the option to somehow get an msys prompt.
As soon the PR https://github.com/netdata/netdata/pull/18253 is merged, I am going to add an option to open it.

@Ferroin and @ktsaou I think we need to add to our TODO list the license (GPL-3) as the first page of the installer, let me know if you have objections.

**Comment by Ferroin** [comment]
@thiagoftsm 

> @Ferroin I am still having some local issues with https://github.com/netdata/netdata/pull/18010 that fixed 3 and 4, let me know how I can help you for we finish this.

I’m working on reproducing the issues you reported locally at the moment, I’ll get back with you if I’m unable to do so.

> @Ferroin since yesterday I am observing this issue with GO:
> 
> ```shell
> + /usr/bin/cmake -S /home/thiago/Netdata/netdata -B /home/thiago/Netdata/netdata/build-msys-MSYS -G Ninja -DCMAKE_INSTALL_PREFIX=/opt/netdata -DBUILD_FOR_PACKAGING=On -DNETDATA_USER=thiago -DENABLE_ACLK=On -DENABLE_CLOUD=On -DENABLE_H2O=Off -DENABLE_ML=On -DENABLE_PLUGIN_GO=On -DENABLE_EXPORTER_PROMETHEUS_REMOTE_WRITE=Off -DENABLE_BUNDLED_JSONC=On -DENABLE_BUNDLED_PROTOBUF=Off
> go: cannot find GOROOT directory: 'go' binary is trimmed and GOROOT is not set
> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
>   Could NOT find Go: (Required is at least version "1.22.0") (found
>   /mingw64/bin/go.exe)
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:601 (_FPHSA_FAILURE_MESSAGE)
>   packaging/cmake/Modules/FindGo.cmake:48 (find_package_handle_standard_args)
>   CMakeLists.txt:212 (find_package)
> ```
> 
> Probably we are missing something in our script that installs dependencies.

No, we’re not missing anything, the Go toolchains shipped by MSYS2 are fundamentally broken in various ways. The preferred fix is to just install Go _natively_ on Windows (the build system will find it and pick it up properly if it’s installed in the default path). The alternative fix is to manually set `GOROOT` correctly in the build environment (though I have no idea what the correct value is in MSYS2).

> @Ferroin and @ktsaou I think we need to add to our TODO list the license (GPL-3) as the first page of the installer, let me know if you have objections.

We absolutely should have the license in the installer, though it’s not _just_ the GPL that needs to be there.
