### ISSUE TITLE
inbound packets dropped inbound 

### ISSUE THREAD

**Issue by MarcusSattler** [netdata/netdata#4536]
All,

So something interesting I came across.  I was able to solve all of my dropped udp packets by increasing the buffers.  This alert still continued to come back on multiple hosts, sometimes not even while under any load.

Doing some digging it appears that while ifconfig will show dropped packets, looking at the interfaces via ethtool -S interface | grep drop I see no drops at all on the interface.  I went ahead and turned on the firewall/ufw on one of the problematic hosts, and since them ifconfig is not showing any inbound packets being dropped.

If you are not running ufw is the best practice here to just this disable this alarm?  

Thanks!

**Comment by ktsaou** [comment]
Can you show your `ethtool` output. On my servers I don't have `dropped` packet counters:

```sh
# ifconfig enp3s0
enp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9000
        ether 40:8d:5c:6f:cb:d0  txqueuelen 1000  (Ethernet)
        RX packets 22328419  bytes 9474224607 (8.8 GiB)
        RX errors 0  dropped 11723  overruns 0  frame 0
        TX packets 21064228  bytes 31390959348 (29.2 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# cat /sys/class/net/enp3s0/statistics/rx_dropped 
11723

# ethtool -S enp3s0
NIC statistics:
     tx_packets: 21033091
     rx_packets: 22300494
     tx_errors: 0
     rx_errors: 0
     rx_missed: 0
     align_errors: 0
     tx_single_collisions: 0
     tx_multi_collisions: 0
     unicast: 21262663
     broadcast: 380801
     multicast: 657030
     tx_aborted: 0
     tx_underrun: 0
```

on another server:

```sh
# ifconfig eth0
eth0: flags=4675<UP,BROADCAST,RUNNING,ALLMULTI,MULTICAST>  mtu 9000
        inet 10.11.12.1  netmask 255.255.255.0  broadcast 10.11.12.255
        ether 74:d4:35:e7:ac:e6  txqueuelen 1000  (Ethernet)
        RX packets 5678701707  bytes 1588293673998 (1.4 TiB)
        RX errors 0  dropped 201513  overruns 0  frame 0
        TX packets 9731916745  bytes 12982994818316 (11.8 TiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

# cat /sys/class/net/eth0/statistics/rx_dropped 
201513

# ethtool -S eth0
NIC statistics:
     tx_packets: 9729490848
     rx_packets: 5677247203
     tx_errors: 0
     rx_errors: 0
     rx_missed: 1067
     align_errors: 0
     tx_single_collisions: 0
     tx_multi_collisions: 0
     unicast: 5668524059
     broadcast: 917730
     multicast: 8723060
     tx_aborted: 0
     tx_underrun: 0
```

Can you check if `ufw` changed any sysctl or if it logs packets dropped at the firewall? Although, I think the firewall should not influence network interface statistics.
But I don't know for sure.

**Comment by efaden** [comment]
I am getting the same error on a virtual bridge.  Thoughts?

**Comment by aleks-mariusz** [comment]
+1, running CentOS 7.5, kernel 3.10.0-862.9.1.el7.x86_64

received alarm on net_drop.br0.. saying:

```
net_drops.br0
inbound packets dropped - 39320998 packets
```

basically it thinks that the drops are in the millions (and the netdata graph for net_drop.br0 shows it averaging around 65000/s)

I guess i am unclear where it's getting this from, since ifconfig reports:

```
$ ifconfig br0
br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.12.100.126  netmask 255.255.255.0  broadcast 10.12.100.255
        inet6 fe80::569f:35ff:fe14:1d44  prefixlen 64  scopeid 0x20<link>
        ether 54:9f:35:14:1d:44  txqueuelen 1000  (Ethernet)
        RX packets 741187622  bytes 632121298726 (588.7 GiB)
        RX errors 0  dropped 17015  overruns 0  frame 0
        TX packets 518362849  bytes 2134614344114 (1.9 TiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

In other words, barely over 17k for the lifetime of this interface ?

**Comment by ktsaou** [comment]
@aleks-mariusz 	could you please post the chart of your br0?

**Comment by aleks-mariusz** [comment]
attaching:
![netdata-issue4536](https://user-images.githubusercontent.com/2719694/48417938-ed9f3e80-e74b-11e8-9023-cc36550c4719.png)

**Comment by aleks-mariusz** [comment]
Additionally this is a screenshot of just the graph (with no alert modal dialog popped up):

![netdata-issue4536-2](https://user-images.githubusercontent.com/2719694/48418049-348d3400-e74c-11e8-9322-4d158170c1ef.png)

**Comment by aleks-mariusz** [comment]
btw ethtool -S is not supported on the bridge interface (nor on the bond0 that is inside the bridge, presuming can't use ethool on virtual interfaces in general).  I can run it on the underlying physical interfaces but there is no dropped fields reported there (and not sure how useful it would be to look at that anyway)

**Comment by ktsaou** [comment]
Please post the output of this:

```
date; cat /proc/net/dev; sleep 5; date; cat /proc/net/dev; 
```

**Comment by aleks-mariusz** [comment]
here ya go:

```
$ date; cat /proc/net/dev; sleep 5; date; cat /proc/net/dev;
Tue Nov 13 18:12:01 GMT 2018
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
 vnet7: 202719941613 367777722    0    0    0     0          0         0 466479691598 323327625    0    0    0     0       0          0
   br0: 632128936498 741230500    0 17015    0     0          0         0 2134643924982 518403696    0    0    0     0       0          0
 vnet4: 271753590679 480278939    0    0    0     0          0         0 131318153618 452304449    0    0    0     0       0          0
 vnet1: 519165912809 533983574    0    0    0     0          0         0 454011650391 493719263    0    0    0     0       0          0
 vnet6: 182949613503 259221372    0    0    0     0          0         0 399122542580 236765680    0    0    0     0       0          0
 bond0: 1263036860348 1658934221    0    0    0     0          0   6855409 2547124549840 2018357925    0    0    0     0       0          0
 vnet3: 400020878311 538995405    0    0    0     0          0         0 106802382490 514472107    0    0    0     0       0          0
    lo: 9626129016 18998905    0    0    0     0          0         0 9626129016 18998905    0    0    0     0       0          0
veth5e12769: 9636803   11249    0    0    0     0          0         0  2872719   13530    0    0    0     0       0          0
 vnet8: 153693283017 242943177    0    0    0     0          0         0 631234761112 538722091    0    0    0     0       0          0
virbr0-nic:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
virbr0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
 vnet0: 616684154135 676109449    0    0    0     0          0         0 416092881019 637201139    0    0    0     0       0          0
 vnet5: 205317020426 422587756    0    0    0     0          0         0 126083462147 393864976    0    0    0     0       0          0
   em3:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
   em1: 814466199492 838879091    0    0    0     0          0   1010176 715365401679 588433814    0    0    0     0       0          0
   em2: 448570660856 820055130    0    0    0     0          0   5845233 1831759148161 1429924111    0    0    0     0       0          0
   em4:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
 vnet2: 496911873066 481968331    0    0    0     0          0         0 324158287545 438563825    0    0    0     0       0          0
 br0:0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
docker0: 47018962  299576    0    0    0     0          0         0 734704050  524487    0    0    0     0       0          0
Tue Nov 13 18:12:06 GMT 2018
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
 vnet7: 202720239505 367778331    0    0    0     0          0         0 466480517128 323328168    0    0    0     0       0          0
   br0: 632128937755 741230508    0 17015    0     0          0         0 2134643929748 518403701    0    0    0     0       0          0
 vnet4: 271753974079 480279618    0    0    0     0          0         0 131318340469 452305078    0    0    0     0       0          0
 vnet1: 519166656639 533984449    0    0    0     0          0         0 454012169420 493720029    0    0    0     0       0          0
 vnet6: 182949852774 259221719    0    0    0     0          0         0 399123095129 236765968    0    0    0     0       0          0
 bond0: 1263036862705 1658934243    0    0    0     0          0   6855414 2547124555326 2018357940    0    0    0     0       0          0
 vnet3: 400021410138 538996091    0    0    0     0          0         0 106802500981 514472774    0    0    0     0       0          0
    lo: 9626129116 18998907    0    0    0     0          0         0 9626129116 18998907    0    0    0     0       0          0
veth5e12769: 9638303   11251    0    0    0     0          0         0  2873301   13533    0    0    0     0       0          0
 vnet8: 153693562258 242943618    0    0    0     0          0         0 631235763127 538723032    0    0    0     0       0          0
virbr0-nic:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
virbr0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
 vnet0: 616685082105 676110464    0    0    0     0          0         0 416093488138 637202094    0    0    0     0       0          0
 vnet5: 205317378857 422588509    0    0    0     0          0         0 126083655395 393865667    0    0    0     0       0          0
   em3:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
   em1: 814466200125 838879093    0    0    0     0          0   1010178 715365402163 588433821    0    0    0     0       0          0
   em2: 448570662580 820055150    0    0    0     0          0   5845236 1831759153163 1429924119    0    0    0     0       0          0
   em4:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
 vnet2: 496912582889 481969068    0    0    0     0          0         0 324158761271 438564527    0    0    0     0       0          0
 br0:0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
docker0: 47020434  299578    0    0    0     0          0         0 734704632  524490    0    0    0     0       0          0
```

**Comment by ktsaou** [comment]
Found it and fixed it in #4653 
I have described the bug in detail there.

**Comment by ktsaou** [comment]
@MarcusSattler 	thank you for reporting this!

**Comment by ktsaou** [comment]
merged the fix.

**Comment by ktsaou** [comment]
please update your netdata and confirm this fixed it.

**Comment by aleks-mariusz** [comment]
actually i'm unsure the original issue that @MarcusSattler opened is the same as the one i provided debug info.. it may be, but his original desc has mention of firewall functionality being related to dropped packets.. i may have inadvertently hijacked his issue because the description sounded "close-enough" to what i and likely @efaden have experienced

may want to confirm with @MarcusSattler his issue is resolved by this too, i'll get back to you if your fix doesn't resolve my issue, but in any case, thanks so much for looking at it and addressing it so lightningly quick!! immmpressivvee!!

**Comment by ktsaou** [comment]
ok, thanks!

@MarcusSattler 	sorry for the confusion.
Could you please check if your issue is resolved too?

**Comment by efaden** [comment]
I updated mine, still having the issue on both of my computers.

**Comment by photis** [comment]
I'm seeing a large number of packets dropped too. 
> RX packets:11791910 errors:0 dropped:76076 overruns:0 frame:0

Netdata constantly sounds the alarm because my ratio of dropped packages for the last 10 minutes exceeds 0.1%

I found this on the Intahrnet:
```
Beginning with kernel 2.6.37, it has been changed the meaning of dropped packet count. Before, dropped packets was most likely due to an error. Now, the rx_dropped counter shows statistics for dropped frames because of:

Softnet backlog full
Bad / Unintended VLAN tags
Unknown / Unregistered protocols
IPv6 frames when the server is not configured for IPv6
[...]

If the rx_dropped counter stops incrementing while tcpdump is running; then it is more than likely showing drops because of the reasons listed earlier.
```
Meanwhile `ifconfig` has this to say:
```
$ sudo ifconfig eth0
eth0      Link encap:Ethernet  HWaddr f4:4d:30:6d:93:92
          inet addr:192.168.1.201  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::f64d:30ff:fe6d:9392/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11791910 errors:0 dropped:76076 overruns:0 frame:0
          TX packets:17464164 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2459415409 (2.2 GiB)  TX bytes:17603379495 (16.3 GiB)
          Interrupt:20 Memory:aa100000-aa120000
```
But `ethtool` finds no fault:
```
$ sudo ethtool -S eth0 | grep rx
     rx_packets: 11788295
     rx_bytes: 2458306572
     rx_broadcast: 139088
     rx_multicast: 129038
     rx_errors: 0
     rx_length_errors: 0
     rx_over_errors: 0
     rx_crc_errors: 0
     rx_frame_errors: 0
     rx_no_buffer_count: 0
     rx_missed_errors: 0
     rx_long_length_errors: 0
     rx_short_length_errors: 0
     rx_align_errors: 0
     rx_flow_control_xon: 0
     rx_flow_control_xoff: 0
     rx_csum_offload_good: 11637919
     rx_csum_offload_errors: 6
     rx_header_split: 0
     alloc_rx_buff_failed: 0
     rx_smbus: 0
     rx_dma_failed: 0
     rx_hwtstamp_cleared: 0
```
Would it be best to just disable this alarm, or is there indeed cause for concern and should I try to dig deeper? Thanks.

Netdata version: v1.12.0-rc2-33-g54beb88 - commit: 4505c9f 
Debian Linux 8
Linux 3.16.0-7-686-pae on i686
Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz, 4 cores

**Comment by meguroyama** [comment]
Hey there still having an issue as of v1.12.0-13

**Comment by efaden** [comment]
I'm still unable to figure it out either.

**Comment by cakrit** [comment]
@meguroyama and @efaden please contribute to the discussion in #5158. I will add a comment there shortly.
