### ISSUE TITLE
Socket proxying through unix socket doesnt work in FreeBSD 12

### ISSUE THREAD

**Issue by Duffyx** [netdata/netdata#5178]
##### Bug report summary
Hi When proxying from NGINX to netdata with a UNIX socket; I can't reach netdata and get the following error on the NGINX proxy; 502 Bad Gateway nginx/1.14.2.

```
NGINX config:
http {
        include mime.types;
        access_log off;
        aio on;
        aio_write on;
        sendfile on;
        tcp_nopush on;
        proxy_pass_request_headers on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        server {
                listen 10.0.0.1:80;
                listen [fd00::1]:80;
                server_name netdata;
                location / {
                        proxy_pass http://unix:/tmp/netdata.sock;
                        proxy_set_header Connection "keep-alive";
                }
        }
}
netdata config:
[global]
        # hostname = %%HOSTNAME%%
        history = 86400
        bind to = unix:/tmp/netdata.sock
        disconnect idle web clients after seconds = 3600
        # glibc malloc arena max for plugins = 1
        # config directory = /usr/local/etc/netdata
        # plugins directory = /usr/local/libexec/netdata/plugins.d
        # web files directory = /usr/local/share/netdata/web
        # cache directory = /var/cache/netdata
        # lib directory = /var/db/netdata
        # log directory = /var/log/netdata
        # host access prefix =
        # home directory = /var/cache/netdata
        # debug flags = 0x00000000
        # debug log = /var/log/netdata/debug.log
        # error log = /var/log/netdata/error.log
        # access log = /var/log/netdata/access.log
        # errors flood protection period = 1200
        # errors to trigger flood protection = 200
        # memory mode = save
        # update every = 1
        # pthread stack size = 2097152
        run as user = root
        web files owner = netdata
        web files group = netdata
        # http port listen backlog = 100
        default port = 19999
        multi threaded web server = yes
        respect web browser do not track policy = yes
        # enable web responses gzip compression = yes
        # web compression strategy = default
        # web compression level = 3
```
The thing is when I use a normal TCP connection for the proxy it works just fine. (127.0.0.1:19999)

Also, I get these messages in nginx error:
```
2019/01/15 22:04:04 [error] 19608#102248: *65 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.121, server: netdata, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/tmp/netdata.sock:/favicon.ico", host: "netdata", referrer: "http://netdata/"
```

And these messages in netdata access log:
```
'2019-01-15 22:04:04: 5: 102074 '[-]:UNIX' 'ACCESS DENIED'
2019-01-15 22:04:04: 5: 102074 '[-]:UNIX' 'DISCONNECTED''
```

Nginx has read/write permissions on the socket so that shouldn't be a problem either.

##### OS / Environment
FreeBSD 12 STABLE

##### Expected behavior
The NGINX proxy simply connects to the netdata socket and serves the web pages.

**Comment by cakrit** [comment]
Please rebuild from the latest on git and let us know if it's resolved. We just merged a fix for #5181

**Comment by Duffyx** [comment]
Hi, I'm tracking the release tags from the FreeBSD pkg repository. We are currently on release 1.11.1
Is that version also effected by the bug you fixed? If so I'll be able to close this bug when 1.12 is out and in our repository. Will come back on this. Thanks.

**Comment by cakrit** [comment]
No release had this bug, it was on a nightly build and on the master repo earlier this week. 1.12 will be released in 2 weeks.

**Comment by Duffyx** [comment]
Hmmm, then its highly likely that my bug isn't solved yet. 
Can I provide any more debugging information?

**Comment by cakrit** [comment]
Can you please switch your web server to static-threaded and let us know what you get in the access log? The multi-threaded web server is already removed from our master repo and everything will be defaulting to static-threaded anyway with 1.12.

**Comment by Duffyx** [comment]
Hi! Sorry this took so long ... I tried again today with single-threaded web server.
My access logs of nginx show nothing related to netdata.
My error logs of nginx show these errors:
`2019/03/21 23:21:53 [error] 41853#101384: *1 writev() failed (32: Broken pipe) while sending request to upstream, client: 10.0.0.124, server: netdata, request: "GET /index.html HTTP/1.1", upstream: "http://unix:/var/run/netdata/netdata.sock:/index.html", host: "netdata"
2019/03/21 23:21:53 [error] 41853#101384: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.124, server: netdata, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/var/run/netdata/netdata.sock:/favicon.ico", host: "netdata", referrer: "http://netdata/index.html"
2019/03/21 23:21:54 [error] 41853#101384: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.124, server: netdata, request: "GET /index.html HTTP/1.1", upstream: "http://unix:/var/run/netdata/netdata.sock:/index.html", host: "netdata"
2019/03/21 23:21:54 [error] 41853#101384: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.124, server: netdata, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/var/run/netdata/netdata.sock:/favicon.ico", host: "netdata", referrer: "http://netdata/index.html"
2019/03/21 23:21:56 [error] 41853#101384: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.124, server: netdata, request: "GET / HTTP/1.1", upstream: "http://unix:/var/run/netdata/netdata.sock:/", host: "netdata"
2019/03/21 23:21:56 [error] 41853#101384: *1 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.124, server: netdata, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/var/run/netdata/netdata.sock:/favicon.ico", host: "netdata", referrer: "http://netdata/"`

Here I updated reverse proxy config of NGINX with documented option by netdata and then get the following

`2019/03/21 23:22:01 [error] 39873#101394: *9 writev() failed (32: Broken pipe) while sending request to upstream, client: 10.0.0.124, server: netdata, request: "GET / HTTP/1.1", upstream: "http://unix:/var/run/netdata/netdata.sock:/", host: "netdata"
2019/03/21 23:22:01 [error] 39492#100437: *11 writev() failed (32: Broken pipe) while sending request to upstream, client: 10.0.0.124, server: netdata, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/var/run/netdata/netdata.sock:/favicon.ico", host: "netdata`

**Comment by cakrit** [comment]
@mmokhi just ported netdata v13.0.0 in the freebsd repo. Can you use that and try again so we can see if you still get the error?
If you have changed the nginx or netdata configs please also paste the new configurations here.

**Comment by Duffyx** [comment]
I still have this issue even with v13. Does anyone have a working config on FreeBSD to proxy the netdata socket through nginx? Would love to see that :)

**Comment by cakrit** [comment]
I installed freebsd on a VM and tried to reproduce it, but I'm at a loss with where everything is located. I didn't even find the link `orig` that should point to the stock config files directory under `/usr/local/etc/netdata`. We'll see if @vlvkobal can help, he's had more experience of freebsd.

**Comment by vlvkobal** [comment]
@Duffyx do you have in your netdata `error.log` something like
```
2019-03-27 13:56:32: netdata ERROR : WEB_SERVER[static1] : (0987@libnetdata:accept_socket  ): DENIED ACCESS to client ''
```
Please post here this error string.

**Comment by Duffyx** [comment]
Yes, correct.

Nginx error gives this:
2019/03/28 21:50:38 [error] 88404#100922: *4 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.124, server: netdata.lan, request: "GET / HTTP/1.1", upstream: "http://unix:/var/run/netdata/netdata.sock:/", host: "netdata.lan"
2019/03/28 21:50:38 [error] 88404#100922: *4 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.124, server: netdata.lan, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/var/run/netdata/netdata.sock:/favicon.ico", host: "netdata.lan", referrer: "http://netdata.lan/"

Netdata error log gives this:
2019-03-28 21:50:38: netdata ERROR : WEB_SERVER[static6] : POLLFD: LISTENER: accept() failed. (errno 1, Operation not permitted)
2019-03-28 21:50:38: netdata ERROR : WEB_SERVER[static4] : DENIED ACCESS to client ''
2019-03-28 21:50:38: netdata ERROR : WEB_SERVER[static4] : POLLFD: LISTENER: accept() failed. (errno 1, Operation not permitted)

**Comment by cakrit** [comment]
@Duffyx are you able to test the fix @vlkobal put in #5756?

**Comment by vlvkobal** [comment]
Merged #5756 but still waiting for feedback.

**Comment by Duffyx** [comment]
Sorry, will test in weekend if thats OK.

**Comment by Duffyx** [comment]
Patch works great, thx!
