### ISSUE TITLE
Netdata running in subfolders not compatible with Netdata.cloud

### ISSUE THREAD

**Issue by PatTheMav** [netdata/netdata#7157]
#### Bug report summary

When configuring two Netdata instances (running on two seperate machines) to be accessible as seperate via Nginx only (as documented in https://docs.netdata.cloud/docs/running-behind-nginx/#as-a-subfolder-for-multiple-netdata-servers-via-one-nginx), the cloud functionality seems to break as Netdata Cloud assumes each Netdata instance to run at the root directory, but not subdirectories.

REST calls to the registry, as well as the magic link all point to the main hostname, but omit the subdirectory under which the given Netdata instance is reachable.

##### OS / Environment

Debian 10

##### Netdata version (ouput of `netdata -V`)

netdata v1.17.1-210-nightly

##### Steps To Reproduce

* Implement nginx-based configuration as described by the Netdata docs
* Open one instance under `https://host/netdata/server/`
* Try to "log in" via the magic link
* Click the magic link
* I haven't been able to fully reproduce the next step, but in some cases the magic link redirects to `https://host/console.html` instead of `https://host/netdata/server/console.html`
* Go to the Netdata Cloud nodes page
* Open the browser's error log
* See failed requests made to `https://host/api/v1/registry` instead of `https://host/netdata/server/api/v1/registry`
* Also adding additional Netdata instances running in separate subfolders doesn't seem to work - they won't appear in the nodes overview and the error log will always show a `touch` event to the cloud agent receiving a `404` response.

##### Expected behavior

Netdata should either be configured or should automatically detect the "real" path under which it is being accessed and use that one to register and contact its nodes.

##### PS

The reason why I chose to run both instances via the same hostname but under seperate paths is due to HTTP Basic auth blocking cross origin REST calls that would otherwise break the cloud dashboard's functionality.

**Comment by cakrit** [comment]
@PatTheMav apologies for not replying sooner. 

This is all going away with the new version of the cloud, coming in ~1 month. Stay tuned!

**Comment by PatTheMav** [comment]
@cakrit So I saw the feature working with subdirectories at around March and now it reverted back to the old behavior of always looking for netdata in a domain's root - the magic link goes straight to `https://host/console.html` again. Maybe a regression?

**Comment by cakrit** [comment]
We deployed a completely refactored front end, written in React. Let us run a couple of tests, to verify we broke the redirect to subdirectories, so we can fix it.

**Comment by cakrit** [comment]
The versions after 1.21.1 should have no problems with the subdirectories. Which version gives you the problem? I just ran some tests with the latest and I don't see issues.

**Comment by PatTheMav** [comment]
@cakrit I always run nightly with daily updates. Current version is `v1.21.1-44-nightly`.

I tested the functionality moments ago and after clicking the magic link I was redirected to the root directory of main domain instead of the sub-folder of the specific netdata instance.

Checking the redirect-flow confirmed it (I replaced the actual domain values):

`https://netdata.cloud/account/sign-in-agent?id=ID&name=DOMAIN.com&origin=https%3A%2F%2FSUBDOMAIN.DOMAIN.com%2F&redirect_uri=https%3A%2F%2FSUBDOMAIN.DOMAIN.com`

**Comment by cakrit** [comment]
Someone will investigate further. Thanks for the info @PatTheMav

**Comment by PatTheMav** [comment]
@cakrit Don't mention it. 👍🏻

**Comment by jacekkolasa** [comment]
@PatTheMav The problem with redirect should be solved since yesterday's nightly build. I  advice however to check it tomorrow, when the new nightly build will be released - we've added one more bugfix, which fixed rare false-negative sign-in state.

**Comment by PatTheMav** [comment]
@jacekkolasa Can't confirm for v1.21.1-83-nightly. Using the magic link still sends me to the root directory of the domain, not the subdirectory the specific Netdata instance is located at.

When clicking the "Sign-in" link in Netdata, the `sign-in-agent` page shows `https://DOMAIN/console.html` as the identifier and not `https://DOMAIN/PATH/console.html`, so it seems that the whole sign-in process is already started with a bad netdata instance path and as such any and all redirect-URLs will point to the wrong path.

I also re-checked the magic link in a private browsing window to avoid localStorage data having an impact.

**Comment by jacekkolasa** [comment]
@PatTheMav you're right, when you access Netdata.Cloud from "Nodes" button, and you are in subpath, the redirect is wrong from magic link. We are very close (days) to releasing completely new Netdata.Cloud, that's why we haven't enough time to test throughly recent bug fix for this issue. The new release will overwrite components in navbars anyway... Are you ok with using "Sign In" button for now? It should work properly.

**Comment by PatTheMav** [comment]
@jacekkolasa I absolutely would be, unfortunately it seems I conflated both issues in my previous comment:

> When clicking the "Sign-in" link in Netdata

Is still true, neither "Sign-in" nor the Nodes button works.

> `https://DOMAIN/console.html`

This is of course true for the Nodes button, the page redirect to by the "Sign-In" button displays `https://DOMAIN/` only, but still missing the correct path.

I'm fine with waiting for the bugfix anyway though.

**Comment by PatTheMav** [comment]
Good news, the new netdata cloud works fine with my setup. I have issues and opinions on the new cloud system, but those are out-of-scope. 😄

**Comment by cakrit** [comment]
Excellent! Nice to hear @PatTheMav
